### ISSUE TITLE
Build fails due to Makefile error

### ISSUE THREAD

**Issue by pizdex** [arthurtilly/rhythmtengoku#2]
When trying to build the ROM, it fails due to a mismatch in sha1sum's output and what the Makefile expects:
`$ make`
`Makefile:115: *** Provided ROM is not correct.  Stop.`

Changing line 114 from
`ifneq ($(shell sha1sum baserom.gba), 67f8adacff79c15d028fffd90de3a77d9ad0602d  baserom.gba)`
to
`ifneq ($(shell sha1sum baserom.gba), 67f8adacff79c15d028fffd90de3a77d9ad0602d *baserom.gba)`
seems to fix the issue.

**Comment by arthurtilly** [comment]
This change causes it to not build for me, are you using WSL?

**Comment by pizdex** [comment]
Hmm, according to wikipedia:
"Note well, if the hash digest creation is performed in text mode instead of binary mode, then there will be two space characters instead of a single space character and an asterisk."
Maybe your sha1sum is running in text mode by default? I'm using cygwin, which I guess requires the binary mode flag for binary data.

**Comment by arthurtilly** [comment]
Alright, I've made the command explicitly run in text mode so you shouldnt run into that issue anymore.
