### ISSUE TITLE
Is this linux only?

### ISSUE THREAD

**Issue by Starpelly** [arthurtilly/rhythmtengoku#57]
There aren't a lot of resources or documentation here, but I would appreciate some clarity on what this works on.

Here's an error I'm getting, I know what it says and how I would fix it, but I feel there's something more I'm missing here.
![image](https://github.com/arthurtilly/rhythmtengoku/assets/24588691/0cf2f7a2-b72f-427a-a6d4-eb424ae07975)

**Comment by arthurtilly** [comment]
Yes, this is mostly intended to be used on Linux, however if you are on Windows you can use WSL which is equally supported. For a installation guide, check the pokeemerald decomp and the steps should be the same, except for also requiring FFMPEG as a package.
